### ISSUE TITLE
Verbose and Non-Operable Paddle Press Options - LZW30-SN

### ISSUE THREAD

**Issue by bgorczyk** [InovelliUSA/SmartThingsEdgeInovelli#4]
The paddle press options for the switch need to be brought in line with the dimmer.  I think at one point the dimmer options were updated/removed on the dimmer, but not on the switch.   For example, "Pressed 2 Times" in inoperable, but "Double Pressed" does.

**Comment by InovelliUSA** [comment]
Thanks for the reminder. I will fix this soon in the other devices.

**Comment by InovelliUSA** [comment]
This has been standardized across all devices. So the button options should be greatly reduced and should be the same on all devices.
