### ISSUE TITLE
Selecting OFF in a routine disables the other parameters from selection

### ISSUE THREAD

**Issue by bgorczyk** [InovelliUSA/SmartThingsEdgeInovelli#5]
Create a routine. Change the default ON to OFF and the parameters below become disabled and cannot be selected. Android app.

**Comment by InovelliUSA** [comment]
I don't know how my driver changes could have done this. Isn't this the behavior for all devices?

**Comment by bgorczyk** [comment]
Confirmed Eric M's comment that this is typical Smartthings behavior.
