### ISSUE TITLE
VZM35-SN - Param 257 Remote Protection Missing in the Driver Settings

### ISSUE THREAD

**Issue by bgorczyk** [InovelliUSA/SmartThingsEdgeInovelli#6]
Presuming that P257 should be present for both the Blue 2-1 and the Blue Fan.  

4/11/23 Edge Driver.  Stock firmware.
![Screenshot_20230409_090054_SmartThings](https://user-images.githubusercontent.com/25494901/231902994-0a043ece-5f7c-460c-9aa6-e6c23befae9d.jpg)
![Screenshot_20230409_090122_SmartThings](https://user-images.githubusercontent.com/25494901/231903002-36514f5e-e6c7-4b0b-bdeb-ca15c8a08f54.jpg)

**Comment by InovelliUSA** [comment]
Took this out of the settings page because once you set it from there you can't unset it unless you are physically at the switch. There is still a capability that can be used in automations so people are less likely to accidentally disable their switches but they can still disable remote that way.
