### ISSUE TITLE
VZW35-SN - Blue Fan - FanSpeed and SwitchLevel Do Not Change to 0 When the Switch is Turned Off

### ISSUE THREAD

**Issue by bgorczyk** [InovelliUSA/SmartThingsEdgeInovelli#7]
The FanSpeed and SwitchLevel attributes do not change to 0 when the switch is turned off.

This can cause a compatibility issue with SharpTools and other tools that do not use the Switch attribute to determine if the fan is off.  SharpTools, for example, uses FanSpeed to determine if the fan is off.  It expects that when the fan is turned off, the speed should drop back to `0` and when you turn it back on, the speed should return to the previously reported value (or the fans default if it always switches back on to a default).  This allows devices that have light switch and fan control to operate at the same time as the switch might be associated with a light switch on a device, but it might be associated with the fan.

**Comment by bgorczyk** [comment]
Note from Josh @ SharpTools:  "I'll see if we can add it as an option to the Fan Tile on our side as well. I've seen a few fan implementations that aren't WWST approved doing this, so it probably wouldn't hurt to have the option within the tile."

**Comment by InovelliUSA** [comment]
This has been fixed in the latest edge driver.
